<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to suporte@tray.net.br so we can send you a copy immediately.
 *
 * @category   Tray
 * @package    Tray_CheckoutApi
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset class="form-list">
    <?php 
          $_code = $this->getMethodCode();
          $_standardPD = Mage::getSingleton('checkoutapi/standard');
          
          $totals = Mage::getSingleton('checkout/session')->getQuote()->collectTotals();  
          Mage::log('########################### Inicio Total Cart Data ###########################', null, 'traycheckout.log');
          Mage::log(Mage::getSingleton('checkout/session')->getQuote()->collectTotals()->getData(), null, 'traycheckout.log');
          Mage::log('########################### Fim Total Cart Data ###########################', null, 'traycheckout.log');
          //$shippingAmount = Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress()->getShippingAmount();  
          $strTcPaymentMethods = $_standardPD->getConfigData("tcPaymentMethods");
          
          if($strTcPaymentMethods == "" || $strTcPaymentMethods == null){
              $tcPaymentMethods = explode(",","3,4,2,5,18,16,15,19,20,25");
          }else{
              $tcPaymentMethods = explode(",",$strTcPaymentMethods);
          }
    ?>
    <style>
        ul li.tcPaymentMethod{
            float: left;
            padding: 5px;
            width: 125px;
            height: 60px;
        }
        ul li input{
            float: left;
            margin-right: 5px;
        }
        ul li img.tcPaymentFlag{
            float: left;
            width: 76px;
            height: 49px;
            background-repeat: no-repeat;
            border-radius: 3px;
            background-color: #f3f3f3;
            box-shadow: 1px 1px 2px #ececec;
            opacity:0.30;
            -moz-opacity: 0.30;
            filter: alpha(opacity=30);
        }
        ul li img.tcPaymentFlagSelected{
            opacity:1 !important;
            -moz-opacity: 1 !important;
            filter: alpha(opacity=100) !important;
        }
        
    </style>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        
        <li class="forma_pagamento" style="float:left;;">
            <ul>
                <li>
                    <label for="tcPaymentMethod"><?php echo Mage::helper('payment')->__('Selecione a forma de pagamento') ?> <span class="required">*</span></label><br/>
                    <input type="hidden" id="tcPaymentMethod" name="payment[traycheckout_payment_code_creditcard]" class="required-entry" value=""/>
                    <ul>
                    <?php
                        $imgSrc = "";
                        foreach ($tcPaymentMethods as $idTcPayment){
                            switch (intval($idTcPayment)){
                                case 2: $imgSrc = "diners-club-international";break;
                                case 3: $imgSrc = "visa";break;
                                case 4: $imgSrc = "mastercard";break;
                                case 5: $imgSrc = "american-express";break;
                                case 15: $imgSrc = "discover";break;
                                case 16: $imgSrc = "elo";break;
                                case 18: $imgSrc = "aura";break;
                                case 19: $imgSrc = "jcb";break;
                                case 20: $imgSrc = "hipercard";break;
                                case 25: $imgSrc = "hiper";break;
                            }
                    ?>
                        <li class="tcPaymentMethod" >                            
                            <img src="<?php echo $this->getSkinUrl('tray/checkoutapi/images/'.$imgSrc.'-flag.svg') ?>" class="tcPaymentFlag" id="tcPaymentFlag<?php echo $idTcPayment;?>" onclick="selectCreditCardTc('<?php echo $idTcPayment;?>','<?php echo number_format((float)$totals->grand_total, 2, '.',''); ?>','<?php echo (Mage::app()->getStore()->isFrontUrlSecure())?Mage::getUrl(''):Mage::getBaseUrl();?>')">
                        </li>
                    <?php
                        }
                    ?>
                    </ul>
                </li>
            </ul>
        </li>
        <li id="displayCcInfo" style="display: block;">
            <ul>
                <li>
                    <div class="input-box">
                        <label for="<?php echo $_code ?>_cc_owner"><?php echo Mage::helper('payment')->__('Name on Card') ?> <span class="required">*</span></label><br/>
                        <input type="text" title="<?php echo Mage::helper('payment')->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->getInfoData('cc_owner') ?>"/>
                    </div>
                </li>
                <li>                   
                    <div class="input-box">
                        <label for="<?php echo $_code ?>_cc_number"><?php echo Mage::helper('payment')->__('Credit Card Number') ?> <span class="required">*</span></label><br/>
                        <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo Mage::helper('payment')->__('Credit Card Number') ?>" class="required-entry input-text validate-cc-number" value="<?php echo $this->getInfoData('cc_number')?>" onkeyup="identifyCreditCardTc(this.value.replace(/ /g,''))" onblur="getSplitValues('<?php echo number_format((float)$totals->grand_total, 2, '.',''); ?>',document.getElementById('tcPaymentMethod').value,'<?php echo Mage::getUrl('', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>')"/>
                    </div>
                </li>
                <li>
                    <div class="input-box">
                        <label for="<?php echo $_code ?>_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> <span class="required">*</span></label><br/>
                        <select id="<?php echo $_code ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="validate-cc-exp required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                        <select id="<?php echo $_code ?>_expiration_yr" style="width:102px;" name="payment[cc_exp_year]" class="required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k ? $k : '' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                </li>
                <li>
                    <div class="input-box">
                        <input type="hidden" id="<?php echo $_code ?>_split_value" name="payment[traycheckout_split_value]" value="<?php echo $this->getInfoData('traycheckout_split_value')?>"/>
                        <label for="<?php echo $_code ?>_split"><?php echo Mage::helper('payment')->__('Parcelas') ?> <span class="required">*</span></label><br/>
                        <select id="<?php echo $_code ?>_split" style="width:252px;" name="payment[traycheckout_split_number]" class="required-entry" onchange="document.getElementById('<?php echo $_code ?>_split_value').value = this.options[this.selectedIndex].text.replace(/.*R\$/,'').replace(/\,/,'.');">
                            <option value="">Parcela(s)</option>
                        </select>
                    </div>
                </li>
                <li>
                    <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                    <div class="input-box">
                        <div class="v-fix">
                            <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
                        </div>
                        <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                    </div>
                </li>
            </ul>
        </li>
    </ul>
    
</fieldset>
