<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to suporte@tray.net.br so we can send you a copy immediately.
 *
 * @category   Tray
 * @package    Tray_CheckoutApi
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$title = "";
$message = "";
?>
<?php

    if($this->getRequest()->getParam("type") == 'G' || $this->getRequest()->getParam("type") == 'V'){
        $frase = 'entrou aqui';
        $title = "Erro ao realizar seu pedido pelo Yapay Intermediador";
        $message = "Ocorreu um erro ao realizar o seu pedido pelo Yapay Intermediador.";

        $hash = explode("/order/", $this->getRequest()->getOriginalRequest()->getRequestUri());
        $hashdecode = explode(":", Mage::getModel('core/encryption')->decrypt($hash[1]));

        $order = Mage::getModel('sales/order')
                ->getCollection()
                ->addFieldToFilter('increment_id', $hashdecode[0])
                ->addFieldToFilter('quote_id', $hashdecode[1])
                ->getFirstItem();


    }else{
        $title = "Erro ao realizar o Retorno Autom&aacute;tico";
        $message = "Ocorreu um erro ao realizar o retorno autom&aacute;tico.";
    }
?>

<style>
    @import url('https://fonts.googleapis.com/css?family=Lato');

    .tituloYapay h1 {
        font-family: "Lato";
        font-weight: 800; 
        color: #293272;    
    }

    .erroDados {
        font-size: 18px;
        line-height: 1.7;
        font-family: "Lato";
        font-weight: 800; 
        color: #293272;  
    }

    .tituloYapay hr {
        height: 4px;
        width: 100%;
        border: none;
        color: #3b812e;
        background-color: #3b812e;
        margin-top: 20px;
        margin-bottom: 30px;
    }

    .descricaoPayment {
        font-family:Lato;
        color: #000;
        font-size: 15px;
        line-height: 1.7;
    }

    .errosResYapay {
        font-family:Lato;
        color: #ff0000;
        font-size: 15px;
        line-height: 1.7;
        font-weight: 400;
    }

    .textoRetornoYapay {
        font-family:Lato;
        padding-left: 30px;
        font-size: 15px;
        line-height: 1.7;
    }

    .textoRetornoYapay strong {
        font-family:Lato;
        color: #3b812e;
    }

    .erroMessageYapay {
        font-family:Lato;
        color: #ff0000;
        text-transform: uppercase;
        font-weight: 800;
        font-size: 16px;
        line-height: 1.7;s
    }

    .textoYapay {
        color: #ff0000;
        font-weight: 800;
    }

    .textoYapay strong {
        color: #000;
        font-weight: 800;
    }


@media only screen and (max-width: 600px) {
    .tituloYapay h1 {
        font-size: 17px;
    }
    .tituloYapay hr {
        height: 2px;
    }

    .descricaoPayment, .textoRetornoYapay {
        font-size: 12px;
        line-height: 1.3;
    }

    .nomePedido {
        font-size: 15px;
    }
    

    
}    


</style>

<div class="page-head tituloYapay">
    
    <h1 class="sub-title"><?php echo $title;?></h2>
    <hr/>
</div>
<table style="width:100%;">
    <tr>
        <td style="width:100%" class="descricaoPayment">
            <p class="erroMessageYapay"><?php echo $message;?></p><br /><br />
            <strong class="erroDados">DADOS DO ERRO</strong><br />
                <?php
                    if($this->getRequest()->getParam("type") == 'V'){
                ?>
            <p class="textoYapay">Não foi possível realizar o pagamento do seu pedido. <strong>Tente novamente ou entre em contato com o vendedor</strong></p><br />

            <strong>Campos:</strong> <strong class="errosResYapay"> <?php echo utf8_decode($this->getRequest()->getParam("codigo"));  ?></strong><br />

            <?php 
                }else{
            ?>

           
            <strong>C&oacute;digo: </strong><strong class="errosResYapay"><?php echo utf8_decode($this->getRequest()->getParam("codigo"));  ?></strong><br />
            <?php 
                }
            ?>
            <strong>Descri&ccedil;&atilde;o: </strong><strong class="errosResYapay"><?php echo $this->getRequest()->getParam("descricao");  ?></strong><br />
        </td>
    </tr>
</table>           