<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to suporte@tray.net.br so we can send you a copy immediately.
 *
 * @category   Tray
 * @package    Tray_CheckoutApi
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>       
<p>
    <strong>
        <?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?>
    </strong>
    <style>
        img.tcPaymentFlag{
            float: left;
            width: 76px;
            height: 49px;
            background-repeat: no-repeat;
            border-radius: 3px;
            background-color: #f3f3f3;
            box-shadow: 1px 1px 2px #ececec;
            margin-right: 10px;
            margin-bottom: 10px;
            margin-top: 5px;
        }
        
    </style>
    <br/>
    <?php
        $imgSrc = "";
        switch (intval($this->getInfo()->getData("cc_type"))){
            case 2: $imgSrc = "diners-club-international";break;
            case 3: $imgSrc = "visa";break;
            case 4: $imgSrc = "mastercard";break;
            case 5: $imgSrc = "american-express";break;
            case 6: $imgSrc = "boleto";break;
            case 7: $imgSrc = "itau";break;
            case 14: $imgSrc = "peela";break;
            case 15: $imgSrc = "discover";break;
            case 16: $imgSrc = "elo";break;
            case 18: $imgSrc = "aura";break;
            case 19: $imgSrc = "jcb";break;
            case 20: $imgSrc = "hipercard";break;
            case 21: $imgSrc = "hsbc";break;
            case 22: $imgSrc = "bradesco";break;
            case 23: $imgSrc = "bb";break;
            case 25: $imgSrc = "hiper";break;
        }
    ?>
    <img src="<?php echo $this->getSkinUrl('tray/checkoutapi/images/'.$imgSrc.'-flag.svg') ?>" class="tcPaymentFlag" />
        
    <?php 
        $tcIdPaymentMethodCreditCard = array("","2","3","4","5","15","16","18","19");
        echo (array_search($this->getInfo()->getData("cc_type"), $tcIdPaymentMethodCreditCard)) ? $this->getInfo()->getData("traycheckout_split_number") . " x R$". number_format((float)$this->getInfo()->getData("traycheckout_split_value"), 2, ',','') : "";
    ?>
    
</p>
<?php echo $this->getLinkPayment($this->getInfo()->getOrder()); ?>


