<?php

switch ($this->getStatusId()){
    case '4':
    case '5':
    case '87':
        $title = "Sua compra foi finalizada com Yapay Intermediador";
        $descriptionPaymentTC = "Sua compra foi finalizada através do Yapay Intermediador.<br/>Estamos aguardando a confirmação do pagamento.";
        break;
    case '6':
        $title = "Sua compra foi finalizada com Yapay Intermediador";
        $descriptionPaymentTC = "Sua compra foi finalizada com sucesso através do Yapay Intermediador.";
        break;
    case '7':
    case '89':
        $title = "Ocorreu um problema ao finalizar a compra pelo Yapay Intermediador";
        $descriptionPaymentTC = "Ocorreu um problema ao finalizar a compra através do Yapay Intermediador.";
        break;
    case '88':
        $title = "Sua compra foi finalizada com Yapay Intermediador";
        $descriptionPaymentTC = "Sua compra foi finalizada através do Yapay Intermediador.<br/>Estamos aguardando a confirmação do pagamento.";
        break;
}
?>


<style>
    @import url('https://fonts.googleapis.com/css?family=Lato');

    .tituloYapay h1 {
        font-family:Lato;
        font-weight: 800; 
        color: #293272;    
    }

    .tituloYapay hr {
        height: 4px;
        width: 100%;
        border: none;
        color: #3b812e;
        background-color: #3b812e;
        margin-top: 20px;
        margin-bottom: 30px;
    }

    .descricaoPayment {
        font-size: 15px;
        line-height: 1.7;
    }

    .textoRetornoYapay {
        padding-left: 30px;
        font-size: 15px;
        line-height: 1.7;
    }

    .textoRetornoYapay strong {
        color: #3b812e;
    }

    .nomePedido {
        color: #293272;
        text-transform: uppercase;
    }

    .tabela {
        width: 100%; 
        font-family:Lato;
        color: #000;
    }

    .page-head {
        line-height: 1.7;
    }

    .buttonYapay {
        border-radius:
        5px; padding: 20px 40px;
        background: #293272;
        color: #FFF;
        font-weight: 800;
        font-size: 17px;
        -webkit-transition: all 0.5s;
        -moz-transition: all 0.5s;
        -o-transition: all 0.5s;
        transition: all 0.5s;
    }    


    .buttonYapay:hover {                
        background-color: #293272;
        box-shadow: 0 7px 7px 0 rgba(0,0,0,0.10), 0 7px 7px 0 rgba(0,0,0,0.10);
        -webkit-transition: all 0.5s;
        -moz-transition: all 0.5s;
        -o-transition: all 0.5s;
        transition: all 0.5s;        
    }

@media only screen and (max-width: 600px) {
    .tituloYapay h1 {
        font-size: 17px;
    }
    .tituloYapay hr {
        height: 2px;
    }

    .descricaoPayment, .textoRetornoYapay {
        font-size: 12px;
        line-height: 1.3;
    }

    .nomePedido {
        font-size: 15px;
    }


    
}    


</style>

<div style="text-align: left">
    <div class="page-head tituloYapay" >
        <h1 class="sub-title"><?php echo $title;?> </h1> 
        <hr/>
    </div>
    <div>
            <table class="tabela">
                <tr>
                    <td style="width:100%">
                        <div  class="descricaoPayment">
                            <?php echo $descriptionPaymentTC;?><br/><br/><br/>
                        </div>
                        <h3><strong class="nomePedido">Dados do Pedido:</strong></h3>
                        <div class="textoRetornoYapay">
                            Seu n&uacute;mero de pedido &eacute;: <strong><?php echo $this->getOrderNumber()?></strong><br />
                            N&uacute;mero da transa&ccedil;&atilde;o no Yapay Intermediador: <strong><?php echo $this->getTransactionId()?></strong><br />
                            Meio de Pagamento: <strong>Yapay Intermediador - <?php echo $this->getPaymentMethodName()?></strong><br />
                            Situa&ccedil;&atilde;o da transa&ccedil;&atilde;o no Yapay Intermediador: <strong><?php echo $this->getStatusName()?></strong><br />
                            <?php if ($this->getPaymentResponse() != '') { ?>
                                Retorno do pagamento na Yapay Intermediador: <strong><?php echo $this->getPaymentResponse() ?></strong><br /><br />
                            <?php } ?>
                        </div>
                        <?php
                        switch ($this->getPaymentMethodId()) {
                                case "6":
                        ?>
                        <button onclick="window.open('<?php echo $this->getUrlPayment()?>');" class="button btn-proceed-checkout btn-checkout buttonYapay" style="" title="Imprimir Boleto" type="button"><span><span>Imprimir Boleto</span></span></button><br />
                        <?php
                            break;
                                case "7":
                                case "14":
                                case "21":
                                case "22":
                                case "23":
                        ?>
                        <button onclick="window.open('<?php echo $this->getUrlPayment()?>');" class="button btn-proceed-checkout btn-checkout buttonYapay" title="Efetuar Transfer&ecirc;ncia Online" type="button"><span><span>Efetuar Transfer&ecirc;ncia Online</span></span></button><br />
                        <?php
                            break;
                        }
                        ?>
                        <br />
                        <br />
                        <!-- <img src="<?php echo $this->getSkinUrl('tray/checkoutapi/images/BannerYapayIntermediador890px.png'); ?>" /> -->
                    </td>
                </tr>
            </table>
    </div>
</div>